test_that("can print lazy_select_query", {
  lf <- lazy_frame(x = 1, y = 2)

  expect_snapshot(
    lazy_select_query(
      x = lf$lazy_query,
      select = quos(
        x_mean = mean(x),
        y2 = y
      ),
      where = quos(y > 1, x == y - 2),
      group_by = quos("x")
    )
  )
})

test_that("select_query() print method output is as expected", {
  mf <- lazy_frame(x = 1, con = simulate_dbi()) |>
    filter(x > 1L) |>
    arrange(x) |>
    head(10) |>
    sql_build()
  expect_snapshot(mf)
})

test_that("queries generated by select() don't alias unnecessarily", {
  lf_build <- lazy_frame(x = 1, y = 1) |>
    select(x) |>
    sql_build()

  lf_render <- sql_render(lf_build, con = simulate_dbi())
  expect_snapshot(lf_render)
})

test_that("queries generated by select() don't alias unnecessarily", {
  expect_snapshot(error = TRUE, lazy_frame(x = 1, y = 1) |> select())
})
