test_that("select_query() print method output is as expected", {
  mf <- lazy_frame(x = 1, con = simulate_dbi()) |>
    filter(x > 1L) |>
    arrange(x) |>
    head(10) |>
    sql_build()
  expect_snapshot(mf)
})

test_that("queries generated by select() don't alias unnecessarily", {
  lf_build <- lazy_frame(x = 1, y = 1) |>
    select(x) |>
    sql_build()

  lf_render <- sql_render(lf_build, con = simulate_dbi())
  expect_snapshot(lf_render)
})

test_that("queries generated by select() don't alias unnecessarily", {
  expect_snapshot(error = TRUE, lazy_frame(x = 1, y = 1) |> select())
})

# Optimisations -----------------------------------------------------------

test_that("optimisation is turned on by default", {
  lf <- lazy_frame(x = 1, y = 2) |> arrange(x) |> head(5)
  qry <- lf |> sql_build()

  expect_equal(qry$from, base_query(table_path('"df"')))
})

test_that("can generate SELECT query with all clauses", {
  lf <- local_memdb_frame("all-clauses", a = 1:3) |>
    mutate(b = a + 1) |>
    distinct() |>
    filter(a > 1) |>
    arrange(a)

  expect_snapshot(lf |> show_query())

  # And check that it returns the correct value
  expect_equal(collect(lf), tibble(a = 2:3, b = a + 1.0))
})

test_that("summarise + head is collapsed", {
  lf <- local_memdb_frame("df", x = 1:10, y = 2) |>
    summarise(y = sum(y, na.rm = TRUE), .by = x) |>
    head(1)
  expect_snapshot(lf |> show_query())

  # And check that it returns the correct value
  expect_equal(collect(lf), tibble(x = 1L, y = 2))
})

test_that("select + arrange/filter is collapsed", {
  lf <- local_memdb_frame("df", x = 1:2, y = 2:1)

  lf_filter <- lf |> filter(x == 1) |> select(y)
  lf_arrange <- lf |> arrange(x) |> select(y)

  expect_snapshot(lf_filter |> show_query())
  expect_snapshot(lf_arrange |> show_query())

  expect_equal(collect(lf_filter), tibble(y = 2))
  expect_equal(collect(lf_arrange), tibble(y = 2:1))
})

test_that("filter + summarise is collapsed", {
  lf <- local_memdb_frame("df", x = 1:2, y = c(1, 10), g = c(1, 1)) |>
    filter(x == 1) |>
    summarise(y = mean(y), .by = g)

  expect_snapshot(lf |> show_query())
  expect_equal(collect(lf), tibble(g = 1, y = 1))
})

test_that("is_select_star() correctly identifies star selects", {
  expect_true(is_select_star("`df`.*"))
  expect_true(is_select_star("*"))

  expect_false(is_select_star(c("`x`", "`y`")))
  expect_false(is_select_star("`stars`"))
})
