context("SQL: escaping")

# Identifiers ------------------------------------------------------------------

ei <- function(...) unclass(escape(ident(c(...))))

test_that("identifiers are doubled quoted", {
  expect_equal(ei("x"), '"x"')
})

test_that("identifiers are comma separated", {
  expect_equal(ei("x", "y"), '"x", "y"')
})

test_that("identifier names become AS", {
  expect_equal(ei(x = "y"), '"y" AS "x"')
})

# Special values ----------------------------------------------------------------

test_that("missing vaues become null", {
  expect_equal(escape(NA), sql("NULL"))
  expect_equal(escape(NA_real_), sql("NULL"))
  expect_equal(escape(NA_integer_), sql("NULL"))
  expect_equal(escape(NA_character_), sql("NULL"))
})

test_that("-Inf and Inf are expanded and quoted", {
  expect_equal(escape(Inf), sql("'Infinity'"))
  expect_equal(escape(-Inf), sql("'-Infinity'"))
})

test_that("logical is SQL-99 compatible (by default)", {
  expect_equal(escape(TRUE), sql("TRUE"))
  expect_equal(escape(FALSE), sql("FALSE"))
  expect_equal(escape(NA), sql("NULL"))
})

# Times -------------------------------------------------------------------

test_that("times are converted to ISO 8601", {
  x <- ISOdatetime(2000, 1, 2, 3, 4, 5, tz = "US/Central")
  expect_equal(escape(x), sql("'2000-01-02T09:04:05Z'"))
})

# Name aliasing -----------------------------------------------------------

test_that("queries generated by select() don't alias unnecessarily", {
  lf_build <- lazy_frame(x = 1) %>%
    select(x) %>%
    sql_build()

  render_odbc <- sql_render(lf_build, con = simulate_odbc())
  render_dbi  <- sql_render(lf_build, con = simulate_dbi())

  expect_equal(render_odbc, sql("SELECT `x`\nFROM `df`"))
  expect_equal(render_dbi,  sql("SELECT \"x\"\nFROM \"df\""))
})

test_that("names_to_as() doesn't alias when ident name and value are identical", {
  x <- ident(name = "name")

  y_odbc <- sql_escape_ident(con = simulate_odbc(), x = x)
  y_dbi  <- sql_escape_ident(con = simulate_dbi(),  x = x)

  expect_equal(names_to_as(y_odbc, names2(x), con = simulate_odbc()), "`name`")
  expect_equal(names_to_as(y_dbi, names2(x),  con = simulate_dbi()),  "\"name\"")
})
