#' Override window order and frame
#'
#' These allow you to override the `PARTITION BY` and `ORDER BY` clauses
#' of window functions generated by grouped mutates.
#'
#' @inheritParams arrange.tbl_lazy
#' @param ... Variables to order by
#' @export
#' @examples
#' library(dplyr, warn.conflicts = FALSE)
#'
#' db <- memdb_frame(g = rep(1:2, each = 5), y = runif(10), z = 1:10)
#' db %>%
#'   window_order(y) %>%
#'   mutate(z = cumsum(y)) %>%
#'   show_query()
#'
#' db %>%
#'   group_by(g) %>%
#'   window_frame(-3, 0) %>%
#'   window_order(z) %>%
#'   mutate(z = sum(x)) %>%
#'   show_query()
window_order <- function(.data, ...) {
  dots <- quos(...)
  dots <- partial_eval_dots(dots, vars = op_vars(.data))
  names(dots) <- NULL

  lazy_query <- add_order(.data, dots)

  .data$lazy_query <- lazy_query
  .data
}

# We want to preserve this ordering (for window functions) without
# imposing an additional arrange, so we have a special op_order
add_order <- function(.data, dots) {
  lazy_query <- .data$lazy_query
  if (!inherits(lazy_query, "lazy_select_query")) {
    out <- lazy_select_query(
      from = lazy_query,
      last_op = "window_order",
      select = syms(set_names(op_vars(lazy_query))),
      order_vars = dots
    )

    return(out)
  }

  # `window_order()` does not produce an `ORDER BY` clause
  lazy_query$order_vars <- dots
  lazy_query
}


# Frame -------------------------------------------------------------------

#' @export
#' @rdname window_order
#' @param from,to Bounds of the frame.
window_frame <- function(.data, from = -Inf, to = Inf) {
  stopifnot(is.numeric(from), length(from) == 1)
  stopifnot(is.numeric(to), length(to) == 1)

  .data$lazy_query$frame <- list(range = c(from, to))
  .data
}
